# Generated by Django 4.2.3 on 2023-07-20 01:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_remove_profilemodel_lastname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilemodel',
            old_name='credit',
            new_name='Credit',
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='Gender',
            field=models.IntegerField(choices=[(1, 'Man'), (2, 'Woman')], default=1),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User Profile'),
        ),
    ]
