# Generated by Django 4.2.3 on 2023-07-16 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ticketSales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='concertModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, null=True)),
                ('SingerName', models.CharField(max_length=100, null=True)),
                ('length', models.IntegerField(null=True)),
                ('Poster', models.ImageField(null=True, upload_to='concertimages/')),
            ],
            options={
                'verbose_name': 'Concert',
            },
        ),
        migrations.CreateModel(
            name='locationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, null=True)),
                ('Address', models.CharField(default='Antalya', max_length=500)),
                ('Phone', models.CharField(max_length=11, null=True)),
                ('Capacity', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Location',
            },
        ),
        migrations.CreateModel(
            name='profileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, null=True)),
                ('LastName', models.CharField(max_length=100, null=True)),
                ('Gender', models.IntegerField(choices=[('Man', 'Man'), ('Woman', 'Woman')], default=1)),
                ('ProfileImage', models.ImageField(null=True, upload_to='profileimages/')),
            ],
            options={
                'verbose_name': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='timeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartDateTime', models.DateTimeField(null=True)),
                ('Seats', models.IntegerField(default=1)),
                ('Status', models.IntegerField(choices=[('Start', 'Ticket sales have started'), ('End', 'Ticket sales are over'), ('Cancel', 'Ticket sales have been cancelled'), ('Saling', 'Ticket sales have been saling')], default=1)),
                ('concertModel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ticketSales.concertmodel')),
                ('locationModel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ticketSales.locationmodel')),
            ],
            options={
                'verbose_name': 'Time',
            },
        ),
        migrations.CreateModel(
            name='ticketModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TicketImage', models.ImageField(null=True, upload_to='ticketimages/')),
                ('Name', models.CharField(max_length=100)),
                ('Price', models.IntegerField()),
                ('profileModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketSales.profilemodel')),
                ('timeModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketSales.timemodel')),
            ],
            options={
                'verbose_name': 'Ticket',
            },
        ),
    ]
