# Generated by Django 4.2.3 on 2023-07-17 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketSales', '0003_locationmodel_concertmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timemodel',
            name='Status',
            field=models.IntegerField(choices=[(1, 'Ticket sales have started'), (2, 'Ticket sales are over'), (3, 'Ticket sales have been cancelled'), (4, 'Ticket sales have been saling')], default=1),
        ),
    ]
