# Generated by Django 4.2.3 on 2023-07-18 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('ticketSales', '0004_alter_timemodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmodel',
            name='profileModel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profilemodel'),
        ),
        migrations.DeleteModel(
            name='profileModel',
        ),
    ]
